### ISSUE TITLE
unable to build zfs-test

### ISSUE THREAD

**Issue by kiranfractal** [zfsonlinux/zfs-test#1]
Hi,

I find it difficult to build zfs-test.

How to build the repository under /usr/src/.. is not clear to me ?

Please make the README more clear.

Thanks.

**Comment by kiranfractal** [comment]
A script to handle all install stuff should make it easy to run without much tweaking.

**Comment by FransUrbo** [comment]
```
# pwd
/usr/src/zfs-test
# /bin/ls -CFl
total 28
-rw-r--r-- 1 root root 2315 Mar  8 17:58 Makefile.am
-rw-r--r-- 1 root root 1156 Mar  8 17:58 README.md
-rwxr-xr-x 1 root root   49 Mar  8 17:58 autogen.sh*
drwxr-xr-x 2 root root 4096 Mar  8 17:58 config/
-rw-r--r-- 1 root root 2097 Mar  8 17:58 configure.ac
drwxr-xr-x 2 root root 4096 Mar  8 17:58 scripts/
drwxr-xr-x 4 root root 4096 Mar  8 17:58 test/
```

The only executable here, the <code>autogen.sh</code> should have been a clue. But I've updated the README.md file somewhat.
