### ISSUE TITLE
ERROR: User zfs-tests is not allowed to run sudo without password.

### ISSUE THREAD

**Issue by kiranfractal** [zfsonlinux/zfs-test#2]
Hi,

I am getting this error when try to run zfs command "sudo make test"

[tcdb@li625-97 zfs-test]$ sudo make test
[sudo] password for tcdb: 
ERROR: User zfs-tests is not allowed to run sudo without password.
make: *** [test_verify] Error 1

Help me to resolve this issue.

Thanks.

**Comment by kiranfractal** [comment]
now I used just "make test" under user tcdb, it is not showing any error but process list shows below output

[root@li625-97 perf-tools]# ps -ef | grep test
tcdb     21650 21469  0 07:13 pts/0    00:00:00 make test
tcdb     21655 21650  0 07:13 pts/0    00:00:00 /bin/bash -c ( if ! id zfs-tests > /dev/null 2>&1; then \??echo "ERROR: You must create a 'zfs-tests' user to run the test as."; \??exit 1; \?   fi; \?   if ! su - zfs-tests -c "sudo ls" > /dev/null 2>&1; then \??echo "ERROR: User zfs-tests is not allowed to run sudo without password."; \??exit 1; \?   fi)
tcdb     21656 21655  0 07:13 pts/0    00:00:00 /bin/bash -c ( if ! id zfs-tests > /dev/null 2>&1; then \??echo "ERROR: You must create a 'zfs-tests' user to run the test as."; \??exit 1; \?   fi; \?   if ! su - zfs-tests -c "sudo ls" > /dev/null 2>&1; then \??echo "ERROR: User zfs-tests is not allowed to run sudo without password."; \??exit 1; \?   fi)
root     21658 21656  0 07:13 pts/0    00:00:00 su - zfs-tests -c sudo ls
root     21667 21409  0 07:14 pts/1    00:00:00 grep test

How to check what tests it is running and what it is doing right now ?

Thanks.

**Comment by eses2014** [comment]
Change /bin/bash to /bin/ksh for the user zfs-test and try running "make test".

**Comment by kiranfractal** [comment]
As you said I am executing as below which is on ksh,

$ pwd
/home/zfs-tests/zfs-test

$ make test

I am not getting any terminal output so far, no any directory created at
/var/tmp.

How to know that it is really executing the testcases ?

The process command output is below,

[root@li625-97 perf-tools]# ps -ef | grep test
root     23791  2084  0 09:01 ?        00:00:00 sshd: zfs-tests [priv]
502      23794 23791  0 09:01 ?        00:00:00 sshd: zfs-tests@pts/0
502      23860 23844  0 09:02 pts/0    00:00:00 make test
502      23865 23860  0 09:02 pts/0    00:00:00 /bin/bash -c ( if ! id
zfs-tests > /dev/null 2>&1; then \??echo "ERROR: You must create a
'zfs-tests' user to run the test as."; \??exit 1; \?   fi; \?   if ! su -
zfs-tests -c "sudo ls" > /dev/null 2>&1; then \??echo "ERROR: User
zfs-tests is not allowed to run sudo without password."; \??exit 1; \?   fi)
502      23866 23865  0 09:02 pts/0    00:00:00 /bin/bash -c ( if ! id
zfs-tests > /dev/null 2>&1; then \??echo "ERROR: You must create a
'zfs-tests' user to run the test as."; \??exit 1; \?   fi; \?   if ! su -
zfs-tests -c "sudo ls" > /dev/null 2>&1; then \??echo "ERROR: User
zfs-tests is not allowed to run sudo without password."; \??exit 1; \?   fi)
root     23868 23866  0 09:02 pts/0    00:00:00 su - zfs-tests -c sudo ls
root     23901 21409  0 09:06 pts/1    00:00:00 grep test

**Comment by eses2014** [comment]
Have you created the test user "zfs-test"? It appears that you do not have the "zfs-user". Create the user and change the shell to /bin/ksh.

**Comment by kiranfractal** [comment]
Yes, I am in user zfs-tests.

Is it zfs-test or zfs-tests ?

**Comment by eses2014** [comment]
You are right... its zfs-tests. You may not require to login as zfs-user. Try running tests from 'root'.

**Comment by kiranfractal** [comment]
Under root, I am getting below error.

[root@li625-97 zfs-test]# ksh

# make test
ERROR: User zfs-tests is not allowed to run sudo without password.
make: *** [test_verify] Error 1

#

**Comment by eses2014** [comment]
Strange.... I don't face any such issue...

**Comment by eses2014** [comment]
How did you changed the shell for zfs-tests user? Have you changed the default shell for zfs-tests in the user profile?

**Comment by kiranfractal** [comment]
I login to zfs-tests and then at shell I type "ksh" and execute the "make
test". I have no idea about what is user profile means.

**Comment by eses2014** [comment]
Which means... the login shell for 'zfs-tests' user to be set as '/bin/ksh'.
From GUI, the login shell can be set by editing the properties of the zfs-tests user.
Or you can try changing the shell in the /etc/passwd file. Find the entry for 'zfs-tests' user and check the shell mentioned at the end of the line. If it is not '/bin/ksh', change it

**Comment by FransUrbo** [comment]
1. The user <code>zfs-tests</code> needs to exists (with <code>.../ksh</code> as a shell)

     ```
     adduser --home /var/tmp/test_results --shell /usr/bin/ksh --gecos "ZFS Test Suite" --disabled-password zfs-tests
     ```
2. The user <code>zfs-tests</code> needs to be able to run <code>sudo</code> without password:

     ```
     echo 'zfs-tests      ALL = (ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
     ```
3. The <code>make test</code> needs to run as <code>root</code>

**Comment by kiranfractal** [comment]
I would like to share my terminal using https://nutty.io/.

Is any willing to look in to it ?

Thanks.

On Tue, Mar 17, 2015 at 4:54 PM, Turbo Fredriksson <notifications@github.com

**Comment by kiranfractal** [comment]
I am getting below error on CentOS 6.6

root@li625-97 perf-tools]#  adduser --home /var/tmp/test_results --shell
/usr/bin/ksh --gecos "ZFS Test Suite" --disabled-password zfs-tests
adduser: unrecognized option '--gecos'
Usage: useradd [options] LOGIN

Options:
  -b, --base-dir BASE_DIR       base directory for the home directory of the
                                new account


On Tue, Mar 17, 2015 at 4:54 PM, Turbo Fredriksson <notifications@github.com

**Comment by FransUrbo** [comment]
> adduser: unrecognized option '--gecos'

I'm sorry if this comes out as rude (not my primary intention and I do apologize for that), but if you can't figure THAT out, you shouldn't be anywhere NEAR this test suite!

I know I've said I want/need help in testing this and I appreciate you trying. But this is "really serious shit"! It WILL (that is a _promise_, not a warning!) blow up in your face, and I can't handhold you every step of the way�

You/anyone wanting to test-drive this will need VERY good shell (especially korn shell) and Linux experience.


So I'm sorry, but could you stop trying and please close this issue (this isn't really a support forum anyway)?

**Comment by kiranfractal** [comment]
Thanks for all your help. Meanwhile I will give my best to resolve it. Thanks.
